# Generated by Django 4.0.3 on 2022-03-08 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile_phone', models.CharField(blank=True, max_length=20)),
                ('user_profile_address', models.CharField(blank=True, max_length=200)),
                ('user_profile_city', models.CharField(blank=True, max_length=50)),
                ('user_profile_state', models.CharField(blank=True, max_length=50)),
                ('user_profile_zipcode', models.CharField(blank=True, max_length=10)),
                ('user_profile_country', models.CharField(blank=True, max_length=50)),
                ('user_profile_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary'), ('Other', 'Other')], default='', max_length=50)),
                ('user_profile_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
