# Generated by Django 4.0.3 on 2022-03-08 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_created_at', models.DateTimeField(auto_now_add=True)),
                ('account_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='accountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type_name', models.CharField(choices=[('Savings', 'Savings'), ('Credit', 'Credit')], default='', max_length=50)),
                ('account_type_minimum_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_type_description', models.CharField(max_length=200)),
                ('account_type_created_at', models.DateTimeField(auto_now_add=True)),
                ('account_type_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], default='', max_length=50)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_description', models.CharField(max_length=200)),
                ('transaction_created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountsAPI.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountsAPI.accounttype'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAPI.userprofile'),
        ),
    ]
